export const FETCH_EXPERIENCES_REQUEST = "FETCH_EXPERIENCES_REQUEST";
export const FETCH_EXPERIENCES_SUCCESS = "FETCH_EXPERIENCES_SUCCESS";
export const FETCH_EXPERIENCES_FAILURE = "FETCH_EXPERIENCES_FAILURE";

export const FETCH_HOMES_REQUEST = "FETCH_HOMES_REQUEST";
export const FETCH_HOMES_SUCCESS = "FETCH_HOMES_SUCCESS";
export const FETCH_HOMES_FAILURE = "FETCH_HOMES_FAILURE";

export const FETCH_HOTELS_REQUEST = "FETCH_HOTELS_REQUEST";
export const FETCH_HOTELS_SUCCESS = "FETCH_HOTELS_SUCCESS";
export const FETCH_HOTELS_FAILURE = "FETCH_HOTELS_FAILURE";
export const HOTELS_SEARCH_KEY = "HOTELS_SEARCH_KEY";
export const HANDLE_SELECT_HOTEL = "HANDLE_SELECT_HOTEL";

export const SIGN_IN_WITH_GOOGLE = "SIGN_IN_WITH_GOOGLE";
export const SIGN_UP_WITH_EMAIL_AND_PASSWORD = "SIGN_UP_WITH_EMAIL_AND_PASSWORD";
export const SIGN_UP_WITH_EMAIL_AND_PASSWORD_FAILURE = "SIGN_UP_WITH_EMAIL_AND_PASSWORD_FAILURE";

export const SIGN_IN_WITH_EMAIL_AND_PASSWORD = "SIGN_IN_WITH_EMAIL_AND_PASSWORD";
export const SIGN_IN_WITH_EMAIL_AND_PASSWORD_FAILURE = "SIGN_IN_WITH_EMAIL_AND_PASSWORD_FAILURE";

export const SIGN_OUT = "SIGN_OUT";
export const AUTH_STATE_CHANGE = "AUTH_STATE_CHANGE";